In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import linprog

import warnings
warnings.filterwarnings('ignore')

In [10]:
c = [1, 5, 9 , 4, 1 , 5, 8, 3, 1]
A = [[1,1,1,0,0,0,0,0,0], 
     [0,0,0,1,1,1,0,0,0], 
     [0,0,0,0,0,0,1,1,1], 
     [1,0,0,1,0,0,1,0,0],
     [0,1,0,0,1,0,0,1,0],
     [0,0,1,0,0,1,0,0,1]]
b = np.ones(6)

res = linprog(c, A_eq=A, b_eq=b, bounds=(0,1), method='simplex')

In [3]:
print(res.x)

[1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [4]:
numero_Personas = 10
numero_Elevadores = 3
numero_Pisos = 20

# Aquí se define el problema LP $$ \max\{c^T \vec{x}\}$$ s.t $$A \vec{x} \leq b$$

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import linprog
# import warnings
# warnings.filterwarnings('ignore')
import sys


def sol_Elevador(numero_Personas, numero_Elevadores, numero_Pisos, posicion_Personas, posicion_Elevadores):

    
    l = numero_Elevadores*numero_Personas
    c = np.zeros(l)
    for i,posP in enumerate(posicion_Personas):
        c[i:i+numero_Elevadores] = np.abs(posicion_Elevadores - posP)
    
    A = np.zeros([l,l])
    
    for i in range(numero_Elevadores):
        A[i:i+numero_]
    
    b = np.zeros()
    b = np.ones(2*numero_Elevadores)
    
    
    res = linprog(c, A_eq=A, b_eq=b, bounds=(0,1), method='simplex')

#     plt.title('Aproximación a la ecuación {0}'.format(orf))
#     plt.plot(xlist, ylist)
#     plt.show()

def printMenu():
    print("\n")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("1 - Solucionar problema del elevador")
    print("0 - Salir")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    
    
    
def printElevador(numero_Personas, numero_Elevadores, numero_Pisos, posicion_Personas, posicion_Elevadores):
    for i in reversed(range(1,numero_Pisos+1)):
        
        k = len(str(i))

        if (i in posicion_Personas) and (i in posicion_Elevadores):
            print( "|"+'-'*14 + "| \n")
            print( "|"+' '*5+str(i)+' '*(6-k) +'███' +"| \n")
            print( "|"+' ' +'●' +' '*9 +'███' +"| \n")
            print( "|"+ '¬█¬'  +' '*8 +'███' +"| \n")
            print( "|"+ ' '+ 'n'  +' '*9 +'███' + "| \n")
                
        elif i in posicion_Personas:
            print( "|"+'-'*14 + "| \n")
            print( "|"+' '*5+str(i)+' '*(9-k) + "| \n")
            print( "|"+' ' +'●' +' '*12 + "| \n")
            print( "|"+ '¬█¬'  +' '*11 + "| \n")
            print( "|"+ ' '+ 'n'  +' '*12 + "| \n")  
            
        elif i in posicion_Elevadores:
            print( "|"+'-'*14 + "| \n")
            print( "|"+' '*5+str(i)+' '*(6-k) +'███' +"| \n")
            print( "|"+' '*11 +'███' +"| \n")
            print( "|"+' '*11 +'███' +"| \n")
            print( "|"+' '*11 +'███' + "| \n")                
                                           
        else:
            print( "|"+'-'*14 + "| \n")
            print( "|"+' '*5 +str(i) +' '*(9-k)+ "| \n")
            print( "|"+' '*14 + "| \n")
            print( "|"+' '*14 + "| \n")
            print( "|"+' '*14 + "| \n")

while True:
    printMenu()
    inputs = input('Seleccione una opción: ')
    if int(inputs[0]) == 1:
        numero_Elevadores = int(input("Ingrese el número de elevadores: "))
        numero_Personas = int(input("Ingrese el número de personas: "))
        numero_Pisos = int(input("Ingrese el número de pisos del edificio: "))
        
        posicion_Personas = np.array([np.random.randint(0,numero_Pisos) for i in range(numero_Personas)])
        posicion_Elevadores = np.array([np.random.randint(0,numero_Pisos) for i in range(numero_Elevadores)])
        
        printElevador(numero_Personas, numero_Elevadores, numero_Pisos, posicion_Personas, posicion_Elevadores)
            
        sol_Elevador(numero_Personas, numero_Elevadores, numero_Pisos, posicion_Personas, posicion_Elevadores)
    else:
        sys.exit(0)
sys.exit(0)





~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 - Solucionar problema del elevador
0 - Salir
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Seleccione una opción: 1
Ingrese el número de elevadores: 3
Ingrese el número de personas: 3
Ingrese el número de pisos del edificio: 5
|--------------| 

|     5        | 

|              | 

|              | 

|              | 

|--------------| 

|     4     ███| 

|           ███| 

|           ███| 

|           ███| 

|--------------| 

|     3        | 

| ●            | 

|¬█¬           | 

| n            | 

|--------------| 

|     2        | 

| ●            | 

|¬█¬           | 

| n            | 

|--------------| 

|     1        | 

|              | 

|              | 

|              | 



ValueError: Invalid input for linprog: A_eq must have exactly two dimensions, and the number of columns in A_eq must be equal to the size of c

In [3]:
numero_Elevadores

3

In [4]:
posicion_Personas

array([3, 2, 0])

In [31]:
    c = np.zeros(numero_Elevadores**2)
    for i,posP in enumerate(posicion_Personas):
        print(i,posP)
        c[i:i+numero_Elevadores] = np.abs(posicion_Elevadores - posP)
    
    A = np.zeros([2*numero_Elevadores,2*numero_Elevadores])
    b = np.ones(2*numero_Elevadores)
    
    
    res = linprog(c, A_eq=A, b_eq=b, bounds=(0,1), method='simplex')

0 0
1 0
2 2
3 5


ValueError: Invalid input for linprog: A_eq must have exactly two dimensions, and the number of columns in A_eq must be equal to the size of c

In [29]:
c[0:3]

array([0., 0., 0.])

In [54]:
print(len(str(10)))

2
